### Basic data types

#### Numbers

Integers and floats work as you would expect from other languages:

In [ ]:
x = 3
print(type(x)) # Prints "<class 'int'>"
print(x)       # Prints "3"

In [ ]:
print(x + 1)   # Addition; prints "4"
print(x - 1)   # Subtraction; prints "2"
print(x * 2)   # Multiplication; prints "6"
print(x ** 2)  # Exponentiation; prints "9"

In [ ]:
x += 1
print(x)  # Prints "4"
x *= 2
print(x)  # Prints "8"

In [ ]:
y = 2.5
print(type(y)) # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

#### Booleans

Python implements all of the usual operators for Boolean logic, but uses English words (`and`, `or`) rather than symbols (`&&`, `||`, etc.):

In [ ]:
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # Logical AND; prints "False"
print(t or f)  # Logical OR; prints "True"
print(not t)   # Logical NOT; prints "False"
print(t != f)  # Logical XOR; prints "True"

#### Strings

Python has great support for strings:

In [ ]:
hello = 'hello'    # String literals can use single quotes
world = "world"    # or double quotes; it does not matter.
print(hello)       # Prints "hello"
print(len(hello))  # String length; prints "5"
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"

#### Loops

You can loop over the elements of a list like this:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)
# Prints "cat", "dog", "monkey", each on its own line.

cat
dog
monkey

- To use ```while``` loop.

In [ ]:
i = 0
while i <5:
    print( i, "th turn")
    i = i+1

- To break for loop implementing ```if``` condition

In [ ]:
for i in range(10):
    print(i)
    if i ==3:
        break

- To test the if conditions:

In [ ]:
import random as random

for i in range(10):
    r = random.uniform(1,10)
    if r<2 and r>0:
        print("It is samaller then 2 and greater then 1","|", r)
    elif r<4 and r>2:
        print("It is samaller then 4 and greater then 2","|", r)
    elif r<6 and r>4:
        print("It is samaller then 6 and greater then 4","|", r)
    elif r<8 and r>6:
        print("It is samaller then 8 and greater then 6","|", r)
    elif r<10 and r>8:
        print("It is samaller then 10 and greater then 8","|", r)

It is samaller then 4 and greater then 2 | 2.410517743617814
It is samaller then 2 and greater then 1 | 1.538375064588924
It is samaller then 8 and greater then 6 | 7.285759129288541
It is samaller then 4 and greater then 2 | 3.394697773325497
It is samaller then 4 and greater then 2 | 2.914781193163869
It is samaller then 8 and greater then 6 | 6.075534618099542
It is samaller then 4 and greater then 2 | 3.2669891450026602
It is samaller then 6 and greater then 4 | 4.071504548968656
It is samaller then 8 and greater then 6 | 7.3289229412263515
It is samaller then 6 and greater then 4 | 5.816515315392462

# Fundamental Data Structure :

The fundamental data structure in python includes

- **Primitive type** ( ***Integer, Float, String***, and ***Boolean***) and
- **Non-Primitive type** ( ***Array, List, Tuples, Dictionary, Set***, and ***File***)

In this tutorial, we are going to discudd about List, Tuples, Set and Dictionary.



### List

List is built in data structure in python. It is
- Mutable i.e., we can change or edite the size of the list by appending, inserting and deleting the elements.
- List can hold heterogeneous objects (e.g., integer, string, boolean)

Lets try to understand the List:

- To initiate a blank List.

In [ ]:
l = []

- To find the type of the object.

In [ ]:
type(l)

list

- To create a list from scratch.

In [ ]:
L = [1,2,3,4,5,6,342,34]

In [ ]:
L

[1, 2, 3, 4, 5, 6, 342, 34]

- Indexing of list.

In [ ]:
L[0],L[1],L[5]

(1, 2, 6)

- Revers indexing is also possible.

In [ ]:
L[-1],L[-2],L[-3]

(6, 5, 4)

- To find the length of list.

In [ ]:
len(L)

6

- To add the element from last.

In [ ]:
L.append(12)
L

[1, 2, 3, 4, 5, 6, 12]

- To find the sum of the elements (if they are of same types like int. double etc)

In [ ]:
sum(L)

33

- To find maximum and minimum of the list

In [ ]:
max(L), min(L)

(12, 1)

- To create a list of heterogeneous element types.

In [ ]:
L = [1,2.0,3,4,5,"Apple",True, False]

- To find the type of elements of a list.

In [ ]:
type(L[1]),type(L[5])

(float, str)

- To create a list of list.

In [ ]:
L = [[1,2,3],[3,4,5],[5,7,9]]

- To find list inside a list.

In [ ]:
L[0]

[1, 2, 3]

In [ ]:
L[0][1]

2

- To add two list. It is not as ususal addition. The elements are accumulated.

In [ ]:
L1 = [1,2,3] ; L2 = [2,4,6]
L1+L2, set(L1+L2)

([1, 2, 3, 2, 4, 6], {1, 2, 3, 4, 6})

- To add element from end of the list

In [ ]:
L = [1,4,2,3,5,6,7]
L.append(100)
L

[1, 4, 2, 3, 5, 6, 7, 100]

- To insert element (100) at specific index (1)

In [ ]:
L = [1,4,2,3,5,6,7]
L.insert(1,100)
L

[1, 100, 4, 2, 3, 5, 6, 7]

- To remove specific element form list. It will remove the first occurance.

In [ ]:
L = [1,4,2,3,5,6,7,4]
L.remove(4)
L

[1, 2, 3, 5, 6, 7, 4]

- To remove the element from specific index

In [ ]:
L = [1,4,2,3,5,6,7]
L.pop(-1)
L

[1, 4, 2, 3, 5, 6]

- To sort the list

In [ ]:
L = [1,10,2,30,5,60,7]
L.sort()
L

[1, 2, 5, 7, 10, 30, 60]

- To reverse the list

In [ ]:
L = [1,4,2,3,5,6,7]
L.reverse()
L

[7, 6, 5, 3, 2, 4, 1]

- List comprehension

In [ ]:
L = [x for x in range(100)]
print(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

In [ ]:
L = [x for x in range(100) if x%2==0]
print(L)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]

In [ ]:
import random as rn
rn.randint(0,100)

59

In [ ]:
import random as rn
R = [rn.randint(0,100) for k in range(200)]
print(R)

[89, 28, 17, 21, 30, 12, 2, 18, 44, 35, 39, 34, 36, 15, 62, 31, 29, 67, 89, 84, 52, 99, 12, 2, 65, 93, 37, 60, 65, 65, 67, 65, 83, 96, 6, 16, 96, 38, 43, 28, 38, 4, 60, 48, 5, 50, 82, 27, 75, 94, 3, 11, 55, 87, 56, 48, 71, 40, 7, 20, 45, 29, 100, 4, 23, 86, 0, 46, 69, 60, 85, 27, 45, 93, 6, 68, 13, 66, 89, 59, 46, 89, 41, 84, 69, 11, 22, 38, 24, 74, 82, 6, 12, 84, 14, 68, 16, 2, 91, 62, 57, 72, 98, 4, 98, 64, 72, 57, 73, 12, 78, 40, 0, 10, 36, 52, 71, 42, 27, 94, 32, 82, 22, 89, 37, 26, 55, 80, 49, 48, 69, 34, 48, 97, 39, 82, 78, 97, 11, 38, 77, 62, 55, 95, 52, 42, 61, 94, 100, 86, 28, 41, 75, 13, 40, 22, 7, 78, 2, 51, 84, 30, 45, 39, 54, 72, 88, 48, 10, 78, 9, 44, 18, 36, 23, 83, 1, 88, 37, 87, 85, 4, 65, 55, 11, 97, 90, 77, 1, 41, 75, 37, 43, 3, 45, 38, 4, 16, 87, 47]

In [ ]:
import collections
#High Performance Counting
C = collections.Counter(R)
print(C)

Counter({37: 5, 17: 5, 67: 5, 15: 4, 99: 4, 88: 4, 61: 4, 54: 4, 96: 4, 80: 4, 51: 4, 83: 4, 14: 4, 10: 3, 78: 3, 27: 3, 49: 3, 62: 3, 38: 3, 48: 3, 94: 3, 66: 3, 81: 3, 72: 3, 95: 3, 1: 3, 21: 3, 100: 3, 40: 3, 28: 3, 43: 3, 29: 2, 16: 2, 7: 2, 74: 2, 60: 2, 64: 2, 85: 2, 50: 2, 39: 2, 44: 2, 8: 2, 90: 2, 58: 2, 0: 2, 79: 2, 24: 2, 98: 2, 93: 2, 22: 2, 68: 2, 42: 2, 86: 2, 30: 2, 41: 2, 77: 2, 59: 2, 34: 2, 4: 2, 31: 2, 57: 2, 6: 2, 73: 2, 45: 1, 69: 1, 91: 1, 71: 1, 75: 1, 87: 1, 70: 1, 47: 1, 82: 1, 18: 1, 9: 1, 26: 1, 55: 1, 56: 1, 23: 1, 52: 1, 33: 1, 13: 1, 2: 1, 46: 1, 36: 1, 53: 1, 92: 1, 84: 1, 12: 1, 20: 1, 5: 1})

In [ ]:
R = [rn.choice(['A','T','G','C']) for i in range(200)]
print(R)

['A', 'T', 'C', 'T', 'T', 'C', 'A', 'C', 'G', 'G', 'A', 'T', 'G', 'G', 'C', 'T', 'G', 'C', 'A', 'T', 'A', 'T', 'T', 'G', 'G', 'G', 'A', 'C', 'G', 'G', 'C', 'C', 'A', 'T', 'A', 'A', 'G', 'G', 'G', 'A', 'A', 'G', 'C', 'C', 'A', 'A', 'C', 'G', 'C', 'G', 'T', 'A', 'A', 'A', 'G', 'G', 'T', 'T', 'A', 'G', 'T', 'T', 'G', 'A', 'C', 'G', 'C', 'C', 'G', 'T', 'C', 'T', 'A', 'C', 'G', 'G', 'G', 'T', 'G', 'A', 'A', 'G', 'C', 'T', 'T', 'C', 'C', 'A', 'A', 'G', 'A', 'C', 'G', 'C', 'T', 'T', 'T', 'T', 'A', 'A', 'T', 'C', 'C', 'T', 'G', 'A', 'C', 'G', 'C', 'A', 'G', 'A', 'C', 'C', 'C', 'A', 'G', 'T', 'A', 'G', 'C', 'A', 'G', 'C', 'G', 'G', 'G', 'T', 'T', 'T', 'A', 'A', 'C', 'T', 'G', 'A', 'T', 'A', 'G', 'G', 'G', 'C', 'G', 'T', 'C', 'C', 'T', 'G', 'G', 'C', 'G', 'A', 'G', 'C', 'C', 'A', 'T', 'A', 'T', 'T', 'C', 'A', 'C', 'T', 'G', 'T', 'G', 'T', 'T', 'T', 'C', 'T', 'G', 'C', 'A', 'G', 'G', 'C', 'T', 'T', 'C', 'G', 'C', 'T', 'C', 'G', 'A', 'G', 'T', 'G', 'A', 'C', 'C', 'T', 'A', 'G', 'C', 'T', 'T', 'T']

In [ ]:
DNA = ''.join(R)
DNA

'ATCTTCACGGATGGCTGCATATTGGGACGGCCATAAGGGAAGCCAACGCGTAAAGGTTAGTTGACGCCGTCTACGGGTGAAGCTTCCAAGACGCTTTTAATCCTGACGCAGACCCAGTAGCAGCGGGTTTAACTGATAGGGCGTCCTGGCGAGCCATATTCACTGTGTTTCTGCAGGCTTCGCTCGAGTGACCTAGCTTT'

### Tuples

Tuples are non-mutable, which means we can ot add or remove elements once tuple is defind.

- To define a tuples from scratch

In [ ]:
t = (2,3,4,5)

- Find type

In [ ]:
type(t)

tuple

- Indexing

In [ ]:
t[1]

3

In [ ]:
L = [(1,2),(2,3),(3,4)]

In [ ]:
L[0][0]

1

- Create a list of tuples

In [ ]:
L = [(1,2),("a","b"),(True, False)]
L

[(1, 2), ('a', 'b'), (True, False)]

### Dictionary

Dictionary organizes the data with key-value pair. Dictionary can be nested with other data types.

- To initiate a dictionary

In [ ]:
D = dict()
DD = {}

- Create a dictionary from scratch

In [ ]:
D = {"fruit":'apple',
    "vegetable" : 'carrot',
    "rice": 2.0,
    'milk': 10,}

- What are keys?

In [ ]:
D.keys()

dict_keys(['fruit', 'vegetable', 'rice', 'milk'])

- What are values?

In [ ]:
D.values()

dict_values(['apple', 'carrot', 2.0, 10])

- Indexing

In [ ]:
D['fruit'], D["rice"]

('apple', 2.0)

- Iteration over key and values

In [ ]:
for key,value in D.items():
    print(key,value)

fruit apple
vegetable carrot
rice 2.0
milk 10

- To update a dictionary

In [ ]:
D.update({"salt": 2.0})
D

{'fruit': 'apple', 'vegetable': 'carrot', 'rice': 2.0, 'milk': 10, 'salt': 2.0}

- To create a list form a Dictionary. Only keys are collected.

In [ ]:
list(D)

['fruit', 'vegetable', 'rice', 'milk']

- To create a list of keys only

In [ ]:
list(D.keys())

['fruit', 'vegetable', 'rice', 'milk']

- To create a list of values

In [ ]:
list(D.values())

['apple', 'carrot', 2.0, 10, 2.0]

- To create Dictionary of with list, tuples and dictionary

In [ ]:
DD = {"names":("John","Harry", "Brat"),\
      "roll no": [1,2,3],\
      "plan":{"first":[12,34,56],"second":[1,3,5]}}

DD

{'names': ['John', 'Harry', 'Brat'],
 'roll no': (1, 2, 3),
 'plan': {'first': [12, 34, 56], 'second': [1, 3, 5]}}

In [ ]:
# Empty set
empty_set = set()
print(type(empty_set))  # <class 'set'>

# Set with initial values
fruits = {'apple', 'banana', 'orange'}
print(fruits)  # {'banana', 'orange', 'apple'}

# Creating set from a list
numbers = set([1, 2, 3, 2, 1])  # Duplicates removed
print(numbers)  # {1, 2, 3}

In [ ]:
colors = {'red', 'green', 'blue'}

# Unordered (no index access)


# No duplicates
unique_nums = {1, 2, 2, 3, 3, 3}
print(unique_nums)  # {1, 2, 3}

# Mutable (can add/remove items)
colors.add('yellow')
print(colors)  # {'red', 'green', 'blue', 'yellow'}

# Length of set
print(len(colors))  # 4

In [ ]:
s = {1, 2, 3}

# Adding elements
s.add(4)
print(s)  # {1, 2, 3, 4}

# Removing elements
s.remove(2)  # Raises KeyError if element doesn't exist
s.discard(5)  # No error if element doesn't exist
print(s)  # {1, 3, 4}

# Pop random element
popped = s.pop()
print(f"Popped: {popped}, Remaining: {s}")

# Clear all elements
s.clear()
print(s)  # set()

# Copy set
new_set = {1, 2, 3}.copy()

In [ ]:
fs = frozenset([1, 2, 3, 3])
print(fs)  # frozenset({1, 2, 3})

In [ ]:
import numpy as np

In [ ]:
nums1 = [1,2,3,4,5]
nums2 = np.array(nums1)

In [ ]:
nums1, nums2

In [ ]:
type(nums1), type(nums2)

In [ ]:
x1 = np.array([3,4,5], dtype='int8')

In [ ]:
x1.dtype

In [ ]:
x1.shape

In [ ]:
x2 = np.arange(20, 50, 2)
x2

In [ ]:
np.linspace(10, 20, 10)

In [ ]:
np.zeros((3,5))

In [ ]:
np.ones((2,5))

In [ ]:
x4 = np.random.random((3,5))
x4

In [ ]:
x4.dtype

In [ ]:
x4.shape

In [ ]:
x4.reshape(5,3)

In [ ]:
x4.T

In [ ]:
I = np.eye(3)
I

In [ ]:
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# first row
A[0]

array([0, 1, 2])

In [ ]:
# second row, second col
A[1,1]

### ```time```

In [ ]:
import time

t1 = time.time()
for i in range(1000001):
    if i==1000000:
        print("done!")

t2 = time.time()
t2-t1

### ```tqdm```

In [ ]:
import time
from tqdm import tqdm

mylist = [i for i in range(100)]

for i in tqdm(mylist):
    time.sleep(0.5)

100%|██████████| 100/100 [00:50<00:00,  1.99it/s]

### ```glob```

In [ ]:
import glob
glob.glob('*.ipynb')

### ```os```

In [ ]:
import os
path = "plot"
os.path.isdir(path)

In [ ]:
path = "1. DataStructure.ipynb"
os.path.isfile(path)

In [ ]:
os.listdir()


### 1. Loading and Exploring the Iris Dataset

In [ ]:
import pandas as pd
from sklearn.datasets import load_iris

# Load the iris dataset
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['species'] = iris.target_names[iris.target]

# Display basic information
print("First 5 rows:")
display(iris_df.head())

print("\nLast 5 rows:")
display(iris_df.tail())

print("\nDataset info:")
iris_df.info()

print("\nBasic statistics:")
display(iris_df.describe())

First 5 rows:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

Last 5 rows:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

Dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

Basic statistics:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

### 2. Selecting Data

In [ ]:
# Select a single column
sepal_length = iris_df['sepal length (cm)']
print("Sepal length column:")
display(sepal_length.head())

# Select multiple columns
sepal_data = iris_df[['sepal length (cm)', 'sepal width (cm)']]
print("\nSepal measurements:")
display(sepal_data.head())

# Select rows by position
first_10 = iris_df.iloc[:10]
print("\nFirst 10 rows:")
display(first_10)

# Select rows by condition
setosa = iris_df[iris_df['species'] == 'setosa']
print("\nSetosa samples:")
display(setosa.head())

Sepal length column:

0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: sepal length (cm), dtype: float64

Sepal measurements:

   sepal length (cm)  sepal width (cm)
0                5.1               3.5
1                4.9               3.0
2                4.7               3.2
3                4.6               3.1
4                5.0               3.6

First 10 rows:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
5,5.4,3.9,1.7,0.4,setosa
6,4.6,3.4,1.4,0.3,setosa
7,5.0,3.4,1.5,0.2,setosa
8,4.4,2.9,1.4,0.2,setosa
9,4.9,3.1,1.5,0.1,setosa

Setosa samples:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

### 3. Data Manipulation

In [ ]:
# Add a new calculated column
iris_df['sepal_ratio'] = iris_df['sepal length (cm)'] / iris_df['sepal width (cm)']
print("DataFrame with new sepal ratio column:")
display(iris_df.head())

# Group by species
grouped = iris_df.groupby('species')
print("\nMean values by species:")
display(grouped.mean())

# Sort by petal length
sorted_df = iris_df.sort_values('petal length (cm)', ascending=False)
print("\nTop 5 flowers by petal length:")
display(sorted_df.head())

DataFrame with new sepal ratio column:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species,sepal_ratio
0,5.1,3.5,1.4,0.2,setosa,1.457143
1,4.9,3.0,1.4,0.2,setosa,1.633333
2,4.7,3.2,1.3,0.2,setosa,1.468750
3,4.6,3.1,1.5,0.2,setosa,1.483871
4,5.0,3.6,1.4,0.2,setosa,1.388889

Mean values by species:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),sepal_ratio
species,,,,,
setosa,5.006,3.428,1.462,0.246,1.470188
versicolor,5.936,2.770,4.260,1.326,2.160402
virginica,6.588,2.974,5.552,2.026,2.230453

Top 5 flowers by petal length:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species,sepal_ratio
118,7.7,2.6,6.9,2.3,virginica,2.961538
122,7.7,2.8,6.7,2.0,virginica,2.750000
117,7.7,3.8,6.7,2.2,virginica,2.026316
105,7.6,3.0,6.6,2.1,virginica,2.533333
131,7.9,3.8,6.4,2.0,virginica,2.078947